### ISSUE TITLE
CONDA_PREFIX_1 error when running df[0].caiman.run()

### ISSUE THREAD

**Issue by X4ndri** [EricThomson/CCN_caiman_mesmerize_workshop_2023#2]
I'm getting this error when trying to run _row.caiman.run()_ in the [mcorr_cnmf.ipynb](https://github.com/nel-lab/mesmerize-core/blob/master/notebooks/mcorr_cnmf.ipynb) demo. This error shows up only in vscode, but when I start Jupyter through the browser, it seems to run fine. Note, I had a caiman conda environment set up, when installing mesmerize-core, I installed it to that environment containing caiman using mamba.
complete traceback below:
KeyError                                  Traceback (most recent call last)
/home/aabdalq/Projects/caiman_analysis/mesmerize_test/notebooks/mcorr_cnmf.ipynb Cell 30 in <cell line: 1>()
----> [1](vscode-notebook-cell://ssh-remote%2Bnimbus/home/aabdalq/Projects/caiman_analysis/mesmerize_test/notebooks/mcorr_cnmf.ipynb#X41sdnNjb2RlLXJlbW90ZQ%3D%3D?line=0) row.caiman.run()

File ~/miniconda3/envs/caiman/lib/python3.10/site-packages/mesmerize_core/caiman_extensions/cache.py:214, in Cache.invalidate.<locals>._invalidate.<locals>.__invalidate(instance, *args, **kwargs)
    208 if pre:
    209     self.cache.drop(
    210         self.cache.loc[self.cache["uuid"] == u].index,
    211         inplace=True
    212     )
--> 214 rval = func(instance, *args, **kwargs)
    216 if post:
    217     self.cache.drop(
    218         self.cache.loc[self.cache["uuid"] == u].index,
    219         inplace=True
    220     )

File ~/miniconda3/envs/caiman/lib/python3.10/site-packages/mesmerize_core/caiman_extensions/common.py:496, in CaimanSeriesExtensions.run(self, backend, wait, **kwargs)
    493     args_str += f" --data-path {get_parent_raw_data_path()}"
    495 # make the runfile
--> 496 runfile_path = make_runfile(
    497     module_path=os.path.abspath(
    498         ALGO_MODULES[self._series["algo"]].__file__
    499     ),  # caiman algorithm
    500     filename=runfile_path,  # path to create runfile
    501     args_str=args_str,
    502 )
    503 try:
    504     self.process = getattr(self, f"_run_{backend}")(
    505         runfile_path, wait=wait, **kwargs
    506     )

File ~/miniconda3/envs/caiman/lib/python3.10/site-packages/mesmerize_core/utils.py:110, in make_runfile(module_path, args_str, filename)
    104 f.write(f"#!/bin/bash\n")
    106 if "CONDA_PREFIX" in os.environ.keys():
    107     f.write(
    108         f'export CONDA_PREFIX={os.environ["CONDA_PREFIX"]}\n'
    109         f'export CONDA_PYTHON_EXE={os.environ["CONDA_PYTHON_EXE"]}\n'
--> 110         f'export CONDA_PREFIX_1={os.environ["CONDA_PREFIX_1"]}\n'
    111     )
    113 elif "VIRTUAL_ENV" in os.environ.keys():
    114     f.write(
    115         f'export PATH={os.environ["PATH"]}\n'
    116         f'export VIRTUAL_ENV={os.environ["VIRTUAL_ENV"]}\n'
    117         f'export LD_LIBRARY_PATH={os.environ["LD_LIBRARY_PATH"]}\n'
    118     )

File ~/miniconda3/envs/caiman/lib/python3.10/os.py:680, in _Environ.__getitem__(self, key)
    677     value = self._data[self.encodekey(key)]
    678 except KeyError:
    679     # raise KeyError with the original key value
--> 680     raise KeyError(key) from None
    681 return self.decodevalue(value)

KeyError: 'CONDA_PREFIX_1'

**Comment by EricThomson** [comment]
Thanks for bringing this up. I would recommend opening this issue over at the `mesmerize-core` package itself (https://github.com/nel-lab/mesmerize-core), where it can be addressed directly. This repo is more for disseminating information about the workshop.

**Comment by kushalkolar** [comment]
Is there a specific reason for running the nb in vscode? mesmerize-core only supports jupyter lab, possible collab in the future.

**Comment by X4ndri** [comment]
@kushalkolar No specific reason other than convenience. I wasn't aware that mesmerize-core only supports jupyter lab. Thanks for the quick response!

**Comment by kushalkolar** [comment]
In general anything other than jupyter lab and collab can be wonky with most packages, companies often put in notebook features into their IDEs as a marketing trick.
